import type { Product } from "../interfaces/inventory";
import { DUMMY_CATEGORIES } from "./categories";

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: "p_1",
    name: "MacBook Pro M3",
    category: DUMMY_CATEGORIES[0],
    price: 160000,
    brand: "Apple",
    quantity: 5,
    description: "14-inch display, 16GB RAM, 512GB SSD. Space Grey.",
  },
  {
    id: "p_2",
    name: "MSI Bravo 15",
    category: DUMMY_CATEGORIES[0],
    price: 75000,
    brand: "MSI",
    quantity: 3,
    description:
      "Gaming laptop with Ryzen 5 and 4GB Graphics. Great for thermals.",
  },
  {
    id: "p_3",
    name: "Mechanical Keyboard",
    category: DUMMY_CATEGORIES[1],
    price: 4500,
    brand: "Logitech",
    quantity: 12,
    description: "Tactile brown switches with customizable RGB lighting.",
  },
  {
    id: "p_4",
    name: "Wireless Gaming Mouse",
    category: DUMMY_CATEGORIES[1],
    price: 3200,
    brand: "Razer",
    quantity: 20,
    description: "Ultra-low latency with 20k DPI optical sensor.",
  },
  {
    id: "p_5",
    name: "27-inch 4K Monitor",
    category: DUMMY_CATEGORIES[1],
    price: 28000,
    brand: "Dell",
    quantity: 7,
    description: "IPS panel with 99% sRGB coverage. Perfect for designers.",
  },
  {
    id: "p_6",
    name: "Wi-Fi 6 Router",
    category: DUMMY_CATEGORIES[2],
    price: 5500,
    brand: "TP-Link",
    quantity: 10,
    description: "Dual-band gigabit router with 4 high-gain antennas.",
  },
  {
    id: "p_7",
    name: "Cat6 Ethernet Cable",
    category: DUMMY_CATEGORIES[2],
    price: 450,
    brand: "D-Link",
    quantity: 50,
    description: "10-meter shielded cable for high-speed local networking.",
  },
  {
    id: "p_8",
    name: "Noise Cancelling Headphones",
    category: DUMMY_CATEGORIES[0],
    price: 24000,
    brand: "Sony",
    quantity: 6,
    description: "Industry-leading ANC with 30-hour battery life.",
  },
  {
    id: "p_9",
    name: "Scientific Calculator",
    category: DUMMY_CATEGORIES[3],
    price: 1200,
    brand: "Casio",
    quantity: 15,
    description: "Standard fx-991EX for engineering and math students.",
  },
  {
    id: "p_10",
    name: "Executive Fountain Pen",
    category: DUMMY_CATEGORIES[3],
    price: 800,
    brand: "Parker",
    quantity: 25,
    description: "Stainless steel body with a fine-point nib.",
  },
  {
    id: "p_11",
    name: "External SSD 1TB",
    category: DUMMY_CATEGORIES[0],
    price: 9500,
    brand: "Samsung",
    quantity: 18,
    description: "Rugged portable storage with USB 3.2 Gen 2 speeds.",
  },
  {
    id: "p_12",
    name: "USB-C Hub (7-in-1)",
    category: DUMMY_CATEGORIES[2],
    price: 2200,
    brand: "Anker",
    quantity: 30,
    description: "Includes HDMI, SD card reader, and Power Delivery port.",
  },
];
